name: Build

on: 
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        id: jdk-8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'zulu'
      - name: Build Snapshot with Maven
        id: build-snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn clean package test --no-transfer-progress --batch-mode
      - name: output
        id: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cat /home/runner/work/_temp/_github_workflow/event.json

